/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
/**
 *
 * @author Ashwini
 */
public class admin extends javax.swing.JFrame {
int flag=0;
int flag1=0;
    /**
     * Creates new form Consumer
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        m1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton19 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        m4 = new javax.swing.JLabel();
        m5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPasswordField4 = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        jPasswordField5 = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setAutoscrolls(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 2000));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(240, 240, 240));
        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(10, 10, 210, 23);

        jButton5.setBackground(new java.awt.Color(0, 0, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(240, 240, 240));
        jButton5.setText("Login");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(10, 30, 210, 23);

        jButton8.setBackground(new java.awt.Color(0, 0, 102));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(240, 240, 240));
        jButton8.setText("Forgot Login Name/Passward");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(10, 50, 210, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 260, 230, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college/final.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 170, 180);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college/11.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 0, 1200, 170);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setText("                        Electricity Billing System   ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 170, 1100, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Admin");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(500, 214, 170, 20);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jPanel5.setPreferredSize(new java.awt.Dimension(1000, 1800));
        jPanel5.setLayout(new java.awt.CardLayout());

        jPanel3.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college/videotogif_2018.09.15_22.52.52.gif"))); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(310, 20, 400, 250);

        jPanel5.add(jPanel3, "card2");

        jPanel4.setLayout(new java.awt.CardLayout());

        jPanel6.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 0, 0));
        jLabel16.setText("Admin Login");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(0, 20, 330, 29);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Login Id :*");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(220, 130, 100, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Password:*");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(230, 210, 90, 17);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel6.add(jTextField1);
        jTextField1.setBounds(430, 130, 230, 30);

        jPasswordField3.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        jPanel6.add(jPasswordField3);
        jPasswordField3.setBounds(430, 200, 230, 30);

        jButton2.setText("Login");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);
        jButton2.setBounds(380, 313, 90, 30);

        jButton9.setText("logout");
        jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9);
        jButton9.setBounds(540, 313, 80, 30);

        jLabel50.setBackground(new java.awt.Color(0, 102, 204));
        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(240, 240, 240));
        jLabel50.setText("Password is case sensitive,please enter the password  carefully                 *indicates a required field");
        jLabel50.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel50.setOpaque(true);
        jPanel6.add(jLabel50);
        jLabel50.setBounds(0, 60, 930, 39);

        jPanel4.add(jPanel6, "card4");

        jPanel7.setLayout(null);

        jButton7.setBackground(new java.awt.Color(0, 0, 102));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton7.setForeground(new java.awt.Color(240, 240, 240));
        jButton7.setText("Summary");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7);
        jButton7.setBounds(250, 50, 450, 140);

        jButton10.setBackground(new java.awt.Color(0, 0, 102));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton10.setForeground(new java.awt.Color(240, 240, 240));
        jButton10.setText("Remove");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton10);
        jButton10.setBounds(250, 420, 450, 140);

        jButton11.setBackground(new java.awt.Color(0, 0, 102));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton11.setForeground(new java.awt.Color(240, 240, 240));
        jButton11.setText("Update");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton11);
        jButton11.setBounds(250, 240, 450, 140);

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton15.setText("Back");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton15);
        jButton15.setBounds(800, 50, 90, 30);

        jPanel4.add(jPanel7, "card5");

        jPanel10.setLayout(null);

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel52.setText("Emp_name");
        jPanel10.add(jLabel52);
        jLabel52.setBounds(110, 110, 102, 28);

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel53.setText("Mob_no");
        jPanel10.add(jLabel53);
        jLabel53.setBounds(110, 150, 102, 26);

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel54.setText("Address*");
        jPanel10.add(jLabel54);
        jLabel54.setBounds(110, 240, 88, 26);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Post");
        jPanel10.add(jLabel5);
        jLabel5.setBounds(120, 290, 64, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Salary");
        jPanel10.add(jLabel6);
        jLabel6.setBounds(120, 340, 102, 26);
        jPanel10.add(jTextField3);
        jTextField3.setBounds(260, 110, 420, 30);

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel10.add(jTextField4);
        jTextField4.setBounds(260, 400, 420, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("            Update Employee Profile");
        jPanel10.add(jLabel11);
        jLabel11.setBounds(30, 40, 650, 40);

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        jPanel10.add(jTextField5);
        jTextField5.setBounds(260, 150, 420, 30);
        jPanel10.add(jTextField6);
        jTextField6.setBounds(260, 230, 420, 30);
        jPanel10.add(jTextField21);
        jTextField21.setBounds(260, 280, 420, 30);
        jPanel10.add(jTextField29);
        jTextField29.setBounds(260, 340, 420, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Email_id");
        jPanel10.add(jLabel13);
        jLabel13.setBounds(120, 410, 90, 17);

        m.setForeground(java.awt.Color.red);
        m.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mKeyTyped(evt);
            }
        });
        jPanel10.add(m);
        m.setBounds(260, 190, 240, 20);

        m1.setForeground(java.awt.Color.red);
        m1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                m1KeyTyped(evt);
            }
        });
        jPanel10.add(m1);
        m1.setBounds(260, 440, 240, 20);

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton4);
        jButton4.setBounds(650, 490, 80, 40);
        jPanel10.add(jTextField7);
        jTextField7.setBounds(710, 50, 90, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton1);
        jButton1.setBounds(865, 50, 70, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.red);
        jLabel7.setText("search using Emp_id");
        jPanel10.add(jLabel7);
        jLabel7.setBounds(690, 24, 160, 20);

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton17.setText("Back");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton17);
        jButton17.setBounds(770, 493, 80, 30);

        jPanel4.add(jPanel10, "card6");

        jPanel15.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setText("summary");
        jPanel15.add(jLabel12);
        jLabel12.setBounds(400, 65, 146, 44);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel15.add(jScrollPane2);
        jScrollPane2.setBounds(35, 178, 904, 365);

        jButton16.setText("display");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton16);
        jButton16.setBounds(35, 128, 80, 32);

        jButton18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton18.setText("Back");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton18);
        jButton18.setBounds(840, 40, 80, 40);

        jPanel4.add(jPanel15, "card5");

        jPanel11.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Remove");
        jPanel11.add(jLabel8);
        jLabel8.setBounds(360, 40, 180, 44);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Select table from which you want to remove records");
        jPanel11.add(jLabel10);
        jLabel10.setBounds(80, 124, 350, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(java.awt.Color.red);
        jPanel11.add(jLabel14);
        jLabel14.setBounds(120, 230, 130, 30);
        jPanel11.add(jTextField8);
        jTextField8.setBounds(350, 230, 110, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton6);
        jButton6.setBounds(560, 230, 100, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "nonindustrial", "industrial", "bill_amt", "bill_unit", "registration", "emp_registration" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel11.add(jComboBox2);
        jComboBox2.setBounds(470, 130, 220, 30);

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton19.setText("Back");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton19);
        jButton19.setBounds(830, 30, 90, 40);

        jPanel4.add(jPanel11, "card6");

        jPanel5.add(jPanel4, "card8");

        jPanel13.setLayout(null);

        jLabel45.setFont(new java.awt.Font("URW Palladio L", 1, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(153, 0, 0));
        jLabel45.setText("Forgot LoginName/Password");
        jPanel13.add(jLabel45);
        jLabel45.setBounds(10, 10, 500, 50);

        jLabel47.setText("Login ID");
        jPanel13.add(jLabel47);
        jLabel47.setBounds(70, 180, 100, 20);

        jLabel48.setText("Registered Email*");
        jPanel13.add(jLabel48);
        jLabel48.setBounds(60, 230, 120, 30);

        jLabel49.setText("Registered Mobile No*");
        jPanel13.add(jLabel49);
        jLabel49.setBounds(40, 330, 140, 20);

        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });
        jTextField26.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField26KeyTyped(evt);
            }
        });
        jPanel13.add(jTextField26);
        jTextField26.setBounds(220, 170, 290, 30);

        jTextField27.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField27KeyTyped(evt);
            }
        });
        jPanel13.add(jTextField27);
        jTextField27.setBounds(220, 230, 360, 30);

        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });
        jTextField28.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField28KeyTyped(evt);
            }
        });
        jPanel13.add(jTextField28);
        jTextField28.setBounds(220, 330, 190, 30);

        jButton13.setForeground(new java.awt.Color(0, 51, 255));
        jButton13.setText("Submit");
        jButton13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton13);
        jButton13.setBounds(360, 430, 100, 30);

        jButton14.setForeground(new java.awt.Color(0, 51, 204));
        jButton14.setText("Clear");
        jButton14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton14);
        jButton14.setBounds(530, 420, 100, 30);

        jLabel51.setBackground(new java.awt.Color(0, 102, 204));
        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(240, 240, 240));
        jLabel51.setText("Please fill the details that you have provided while registration                        *indicates a required field");
        jLabel51.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel51.setOpaque(true);
        jPanel13.add(jLabel51);
        jLabel51.setBounds(0, 60, 980, 40);

        m4.setForeground(java.awt.Color.red);
        m4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                m4KeyTyped(evt);
            }
        });
        jPanel13.add(m4);
        m4.setBounds(220, 370, 340, 20);

        m5.setForeground(java.awt.Color.red);
        m5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                m5KeyTyped(evt);
            }
        });
        jPanel13.add(m5);
        m5.setBounds(220, 270, 340, 20);

        jPanel5.add(jPanel13, "card7");

        jPanel12.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel15.setText("New password");
        jPanel12.add(jLabel15);
        jLabel15.setBounds(147, 170, 150, 60);
        jPanel12.add(jPasswordField4);
        jPasswordField4.setBounds(440, 170, 234, 34);

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel19.setText("Change Password");
        jPanel12.add(jLabel19);
        jLabel19.setBounds(265, 21, 260, 67);
        jPanel12.add(jPasswordField5);
        jPasswordField5.setBounds(440, 250, 234, 32);

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel21.setText("Confirm Password");
        jPanel12.add(jLabel21);
        jLabel21.setBounds(147, 265, 170, 40);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton12.setText("SUBMIT");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton12);
        jButton12.setBounds(359, 415, 170, 44);

        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel22.setText("Login Id");
        jPanel12.add(jLabel22);
        jLabel22.setBounds(156, 116, 140, 40);
        jPanel12.add(jTextField2);
        jTextField2.setBounds(440, 120, 234, 29);

        jPanel5.add(jPanel12, "card6");

        jPanel1.add(jPanel5);
        jPanel5.setBounds(290, 250, 1000, 1800);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//       jPanel5.removeAll();
  //      jPanel5.repaint();
    //    jPanel5.revalidate();

      //  jPanel5.add(jPanel3);
        //jPanel5.repaint();
       // jPanel5.revalidate();
   try
     {
      portal p=new portal();
     p.setVisible(true);
     this.setVisible(false);
     }
     catch(Exception e)
     {
         
     }     
    
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();

        jPanel5.add(jPanel6);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();

        jPanel5.add(jPanel13);
        jPanel5.repaint();
        jPanel5.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();

        jPanel5.add(jPanel15);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();

        jPanel5.add(jPanel11);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     try{
            flag=0;
            int lname= Integer.parseInt(jTextField1.getText());
            String pw= new String(jPasswordField3.getPassword());

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Project","root","root");
            Statement st = cn.createStatement();

            ResultSet rs=st.executeQuery("select * from emp_registration");
            while(rs.next())
            {
                flag=0;
                int eid=rs.getInt(1);
                String en=rs.getString(2);
                long mn=rs.getLong(3);
                String a=rs.getString(4);
                String post=rs.getString(5);
                int s=rs.getInt(6);
                String Email=rs.getString(7);
                String p=rs.getString(8);
                if(eid==lname&&p.equals(pw)&&(post.equals("Admin")||post.equals("admin")))
                {
                    jPanel5.removeAll();
                    jPanel5.repaint();
                    jPanel5.revalidate();

                    jPanel5.add(jPanel7);
                    jPanel5.repaint();
                    jPanel5.revalidate();
                    break;
                }
                else
                {
                   flag=1;
                   
                }
            }
            if(flag==1)
            {
                 JOptionPane.showMessageDialog(this,"Does not matches");
            }
        }
        catch(Exception e)
        {
            System.out.print(e);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();

        jPanel5.add(jPanel10);
        jPanel5.repaint();
        jPanel5.revalidate();
   
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try{
            int id= Integer.parseInt(jTextField26.getText());
            String r_name= jTextField27.getText();
            long Mob_no=Long.parseLong(jTextField28.getText());

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Project","root","root");
            Statement st = cn.createStatement();

            ResultSet rs=st.executeQuery("select * from emp_registration");
            while(rs.next())
            {
                flag=0;
                int r=rs.getInt(1);
                String s1=rs.getString(2);
                long mn=rs.getLong(3);
                String ad=rs.getString(4);
                String sz=rs.getString(5);
                int r1=rs.getInt(6);
                String rt=rs.getString(7);
                String ea=rs.getString(8);
                if(r==id)
                {
                    jPanel5.removeAll();
                    jPanel5.repaint();
                    jPanel5.revalidate();

                    jPanel5.add(jPanel12);
                    jPanel5.repaint();
                    jPanel5.revalidate();
                    break;
                }
                else
                {
                    flag=1;
                }
                if(flag==1)
                {
                    
                   JOptionPane.showMessageDialog(this,"Does not matches");
                }
            }
        }
        catch(Exception e)
        {
            System.out.print(e);

        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
            jTextField26.setText(" ");
            jTextField27.setText(" ");
            jTextField28.setText(" ");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

        try{
            int L_name= Integer.parseInt(jTextField2.getText());
            String password= new String(jPasswordField4.getPassword());
            String confirmpassword= new String(jPasswordField5.getPassword());
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Project","root","root");
            Statement st = cn.createStatement();

            // String query = null;
            // st.executeUpdate("insert into Registration values("+C_no+",'"+M_no+"','"+Email+"','"+L_name+"','"+Password+"')");
            if(password.equals(confirmpassword))
            {

                JOptionPane.showMessageDialog(this,"Password Change Successfuly","success",JOptionPane.INFORMATION_MESSAGE);
                st.executeUpdate("update  Emp_Registration set Password='"+password+"' where Emp_id= '"+L_name+"'");
                System.out.print("Insert Successfuly!!!!!!!!!!!!");
            }
            else{

                JOptionPane.showMessageDialog(this,"Check userName",password,WIDTH);
                System.out.print("Registration Faild!!!!!!!!!!!");
            }

        }
        catch(HeadlessException | NumberFormatException | SQLException e)
        {
            System.out.print(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void m4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_m4KeyTyped

    private void m5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_m5KeyTyped

    private void jTextField27KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField27KeyTyped
        // TODO add your handling code here:
        // TODO add your handling code here:
      if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", jTextField27.getText())))
        {
            m5.setText("Plese Enter Valid Email Address");
        }
        else
        {m5.setText("");}


    }//GEN-LAST:event_jTextField27KeyTyped

    private void jTextField28KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField28KeyTyped
        // TODO add your handling code here:
         Pattern pat=Pattern.compile("^[7-9][0-9]{8}$");
         Matcher man=pat.matcher(jTextField28.getText());
        if(man.matches())
      {
       
            m4.setText("");
        }
        else {
            m4.setText("Plese Enter Valid Mobile Number");
            
        }
        

    }//GEN-LAST:event_jTextField28KeyTyped

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        try{

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Project","root","root");
            Statement st = cn.createStatement();

            ResultSet rs=st.executeQuery("select * from emp_registration");
            jTextArea1.setText(" ");
            jTextArea1.append(" ");
            jTextArea1.append("\tEmp_id\tEmp_name\tMob_no\tAddress\tPost\tSalary\tEmail_id\tPassword\n");
            jTextArea1.append("-------------------------------------------------------------------------------------------------------------\n ");
            while(rs.next())
            {
                int r=rs.getInt("Emp_id");
                String s1=rs.getString("Emp_name");
                long mn=rs.getLong("Mob_no");
                String ad=rs.getString("Address");
                String sz=rs.getString("Post");
                int r1=rs.getInt("Salary");
                String rt=rs.getString("Email_id");
                String ea=rs.getString("Password");
                jTextArea1.append("\t"+r+"\t"+s1+"\t"+mn+"\t"+ad+"\t"+sz+"\t"+r1+"\t"+rt+"\t"+ea+"\n");
            }
        }
        catch(Exception e)
        {
            System.out.print(e);
        }

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
       jTextField1.setText(" ");
       jPasswordField3.setText("");
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();

        jPanel5.add(jPanel3);
        jPanel5.repaint();
        jPanel5.revalidate();
   
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", jTextField4.getText())))
        {
            m1.setText("Plese Enter Valid Email Address");
        }
        else
        {m1.setText("");}

    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        Pattern pat=Pattern.compile("^[7-9][0-9]{8}$");
        Matcher man=pat.matcher(jTextField5.getText());
        m.setText("Plese Enter Valid Mobile Number");
        if(man.matches())
        {

            m.setText("");
        }

    }//GEN-LAST:event_jTextField5KeyTyped

    private void mKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_mKeyTyped

    private void m1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_m1KeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
             int Emp_id=Integer.parseInt(jTextField7.getText());           
             int Salary=Integer.parseInt(jTextField29.getText());
             long Mob_no=Long.parseLong(jTextField5.getText());
             String Emp_name=jTextField3.getText();
             String Email_id=jTextField4.getText();
             String Address=jTextField6.getText();
             String Post=jTextField21.getText();
              Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Project","root","root");
                Statement st = cn.createStatement();
              st.executeUpdate("update  Emp_Registration set Emp_name='"+Emp_name+"' where Emp_id= "+Emp_id+"");
              st.executeUpdate("update  Emp_Registration set Mob_no='"+Mob_no+"' where Emp_id= "+Emp_id+"");
              st.executeUpdate("update  Emp_Registration set Email_id='"+Email_id+"' where Emp_id= "+Emp_id+"");
              st.executeUpdate("update  Emp_Registration set Address='"+Address+"' where Emp_id= "+Emp_id+"");
              st.executeUpdate("update  Emp_Registration set Post='"+Post+"' where Emp_id= "+Emp_id+"");
              st.executeUpdate("update  Emp_Registration set Salary="+Salary+" where Emp_id= "+Emp_id+"");
              System.out.print("Insert Successfuly!!!!!!!!!!!!");
              JOptionPane.showMessageDialog(this,"Employee Login Successfuly \n your Id:"+Emp_id,"success",JOptionPane.INFORMATION_MESSAGE);
                           
            
       }
        catch(HeadlessException | NumberFormatException | SQLException e)
        {
        System.out.print(e);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    try{
            int Emp_id=Integer.parseInt(jTextField7.getText());
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Project","root","root");
            Statement st = cn.createStatement();

            ResultSet rs=st.executeQuery("select * from emp_registration");
            while(rs.next())
            {flag1=0;
                int r=rs.getInt("Emp_id");
                String s1=rs.getString("Emp_name");
               // long mn=rs.getLong("Mob_no");
                String mn=rs.getString("Mob_no");
                String ad=rs.getString("Address");
                String sz=rs.getString("Post");
               // int r1=rs.getInt("Salary");
                String r1=rs.getString("Salary");
                String rt=rs.getString("Email_id");
                String ea=rs.getString("Password");
                if(Emp_id==r)
                {
                    
                    System.out.println("ok");
                    jTextField29.setText(r1);
                    jTextField5.setText(mn);
                    jTextField3.setText(s1);
                    jTextField4.setText(rt);
                    jTextField6.setText(ad);
                    jTextField21.setText(sz);
                    break;
                }
                else
                {
                    flag1=1; 
                    
                }               
           }
            if(flag1==1)
            {JOptionPane.showMessageDialog(this,"Invaild Emp_id");}
        }
        catch(Exception e)
        {
            System.out.print(e);
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed
/**/
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
            int id=Integer.parseInt(jTextField8.getText());
            String choice=(String)jComboBox2.getSelectedItem()+"";
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Project","root","root");
            Statement st = cn.createStatement();
            if(choice.equals("emp_registration"))
            {
                st.executeUpdate("delete from emp_registration where Emp_id="+id+"");
                JOptionPane.showMessageDialog(this,"Deleted Successfuly");
                System.out.print("Deleted Successfuly!!!!!!!!!!!!");

            }
            else if(choice.equals("registration"))
            {
                st.executeUpdate("delete from registration where consumer_no="+id+"");
                JOptionPane.showMessageDialog(this,"Deleted Successfuly");
                System.out.print("Deleted Successfuly!!!!!!!!!!!!");
            }
            else if(choice.equals("nonindustrial"))
            {
                st.executeUpdate("delete from non_industrial where consumer_no="+id+"");
                JOptionPane.showMessageDialog(this,"Deleted Successfuly");
                System.out.print("Deleted Successfuly!!!!!!!!!!!!");
            }
            else if(choice.equals("industrial"))
            {
                st.executeUpdate("delete from industrial where consumer_no="+id+"");
                JOptionPane.showMessageDialog(this,"Deleted Successfuly");
                System.out.print("Deleted Successfuly!!!!!!!!!!!!");
            }
            else if(choice.equals("bill_amt"))
            {
                st.executeUpdate("delete from bill_amt where consumer_no="+id+"");
                JOptionPane.showMessageDialog(this,"Deleted Successfuly");
                System.out.print("Deleted Successfuly!!!!!!!!!!!!");
            }
            else if(choice.equals("bill_unit"))
            {
                st.executeUpdate("delete from bill_unit where consumer_no="+id+"");
                JOptionPane.showMessageDialog(this,"Deleted Successfuly");
                System.out.print("Deleted Successfuly!!!!!!!!!!!!");
            }

        }

        catch(HeadlessException | NumberFormatException | SQLException e)
        {
            System.out.print(e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String choice=(String)jComboBox2.getSelectedItem()+"";
        if(choice.equals("emp_registration"))
        {
           jLabel14.setText("Enter Emp_id");
        }
        else
        {
           jLabel14.setText("Enter consumer_no");            
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();

        jPanel5.add(jPanel6);
        jPanel5.repaint();
        jPanel5.revalidate();
   
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();

        jPanel5.add(jPanel6);
        jPanel5.repaint();
        jPanel5.revalidate();
   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();

        jPanel5.add(jPanel7);
        jPanel5.repaint();
        jPanel5.revalidate();
   
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();

        jPanel5.add(jPanel7);
        jPanel5.repaint();
        jPanel5.revalidate();
   
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        String con_no=jTextField1.getText(); 
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE ||(con_no.length()==3))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField26KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField26KeyTyped
        // TODO add your handling code here:
        String con_no=jTextField26.getText(); 
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE ||(con_no.length()==3))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField26KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel m;
    private javax.swing.JLabel m1;
    private javax.swing.JLabel m4;
    private javax.swing.JLabel m5;
    // End of variables declaration//GEN-END:variables
}
